[package]
name = "tango-bench"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Tango benchmarking harness"
homepage = "https://github.com/bazhenov/tango"
documentation = "https://docs.rs/tango-bench"
repository = "https://github.com/bazhenov/tango"
readme = "../README.md"
categories = ["development-tools", "development-tools::profiling"]
keywords = ["benchmarks", "performance"]

[dependencies]
clap = { version = "^4.4", features = ["derive"] }
libloading = "^0.8"
num-traits = "^0.2"
rand = { version = "^0.8", features = ["small_rng"] }

[target.'cfg(target_os = "linux")'.dependencies]
goblin = "^0.7"
scroll = "^0.11"
tempfile = "^3.8"

[dev-dependencies]
criterion = "^0.5"

[features]
align = []
hw_timer = []
aa_test = []

[[bench]]
name = "criterion"
harness = false

[[bench]]
name = "tango-bench"
harness = false

[[bench]]
name = "tango-faster"
harness = false

[[bench]]
name = "tango-slower"
harness = false
